/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hastatakip;

import static hastatakip.JHastayiSil.flagHastayiSil;
import static hastatakip.JTable.ayiriciTcNo;
import static hastatakip.JTable.infoHastaIsmi;
import static hastatakip.JTable.infoMuayene;
import static hastatakip.JTable.infoSaat;
import static hastatakip.JTable.infoSikayet;
import static hastatakip.JTable.infoTahlil;
import static hastatakip.JTable.infoTarih;
import static hastatakip.JTable.infoTcNo;
import static hastatakip.JTable.infoTedavi;
import static hastatakip.JTable.infoTeshis;
import static hastatakip.JTable.words;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JLabel;

/**
 *
 * @author esmasert
 */
public class JHastaKaydiYok extends javax.swing.JFrame {

    /** Creates new form HastaBilgileri */
    public JHastaKaydiYok() {
        initComponents();
                
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        setDefaultCloseOperation(JYeniHastaRandevuBilgileri.DISPOSE_ON_CLOSE);
        
        JTable nc = new JTable();
        
        nc.putLabelText(lblHastaAdiSoyadi,infoHastaIsmi);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        label1 = new java.awt.Label();
        lblHastaAdiSoyadi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnYeniBulguEkle = new javax.swing.JButton();
        btnGeriDon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHBGoster = new javax.swing.JButton();
        btnHastayiSil = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHastaAdiSoyadi.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHastaAdiSoyadi.setForeground(new java.awt.Color(0, 102, 102));
        lblHastaAdiSoyadi.setText("Hasta Adı Soyadı");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 136, 196));
        jLabel2.setText("Hasta Randevu Bilgileri");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("En Son Kaydediler Bilgiler:");

        btnYeniBulguEkle.setText("Muayene Ekle");
        btnYeniBulguEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniBulguEkleActionPerformed(evt);
            }
        });

        btnGeriDon.setText("Geri Dön");
        btnGeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriDonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hasta Kaydı Bulunamadı!");

        btnHBGoster.setText("Hasta Bilgilerini Goster");
        btnHBGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHBGosterActionPerformed(evt);
            }
        });

        btnHastayiSil.setText("Hastayi Sil");
        btnHastayiSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHastayiSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnHastayiSil, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHastaAdiSoyadi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHBGoster)))
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(373, 373, 373))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGeriDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnYeniBulguEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHastaAdiSoyadi)
                    .addComponent(btnHBGoster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHastayiSil)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYeniBulguEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeriDon))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYeniBulguEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniBulguEkleActionPerformed
        // TODO add your handling code here:
        
        JYeniHastaBulgulari YeniHastaBulgulariFrame = new JYeniHastaBulgulari();
        YeniHastaBulgulariFrame.setVisible(true);
        
        dispose();

            
        //setVisible(false); //you can't see me!
        //dispose(); //Destroy the JFrame object
        
    }//GEN-LAST:event_btnYeniBulguEkleActionPerformed

    private void btnGeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriDonActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_btnGeriDonActionPerformed

    private void btnHastayiSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHastayiSilActionPerformed
        // TODO add your handling code here:
        
        JHastayiSil HastayiSilFrame = new JHastayiSil();
        HastayiSilFrame.setVisible(true);
        
        System.out.println("\n FLLAAAGGGG");
        System.out.println(flagHastayiSil);

        if(flagHastayiSil == 1){
             
            System.out.println(" LOLOLOLOLOLOLOLOLOLOLO ");
            System.out.println(ayiriciTcNo);
        }
        
        //dispose();
        
    }//GEN-LAST:event_btnHastayiSilActionPerformed

    private void btnHBGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHBGosterActionPerformed
        // TODO add your handling code here:
        
        JHastaBilgileriniGosterVeGuncelle HastaBilgileriniGosterVeGuncelleFrame = new JHastaBilgileriniGosterVeGuncelle();
        HastaBilgileriniGosterVeGuncelleFrame.setVisible(true);
        
    }//GEN-LAST:event_btnHBGosterActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHastaKaydiYok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHastaKaydiYok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHastaKaydiYok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHastaKaydiYok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHastaKaydiYok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeriDon;
    private javax.swing.JButton btnHBGoster;
    private javax.swing.JButton btnHastayiSil;
    private javax.swing.JButton btnYeniBulguEkle;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private java.awt.Label label1;
    private javax.swing.JLabel lblHastaAdiSoyadi;
    // End of variables declaration//GEN-END:variables

}
