/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastatakip;

import static hastatakip.JTable.DTwords;
import static hastatakip.JTable.DogumTarihiWords;
import static hastatakip.JTable.ayiriciTcNo;
import static hastatakip.JTable.infoDogumTarihi;
import static hastatakip.JTable.infoHastaIsmi;
import static hastatakip.JTable.infoTcNo;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.Year;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author esmasert
 */
public class JHastaBilgileriniGosterVeGuncelle extends javax.swing.JFrame {

    /**
     * Creates new form JHastaBilgileriniGosterVeGuncelle
     */
    
    String[] HBilgileri = null;
    String HDTarihi = null;
    int FlagIS = 0; 
    int FlagT = 0;
    int FlagAd = 0;
    
    
    public JHastaBilgileriniGosterVeGuncelle() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        setDefaultCloseOperation(JYeniHastaRandevuBilgileri.DISPOSE_ON_CLOSE);
        
        System.out.println("\nIsteee buradaaaaaa");
        System.out.println(ayiriciTcNo);
        
        
        txtTcNo.setEditable(false);
        txtDogumTarihi.setForeground(new java.awt.Color(0, 0, 0));
        
        
        try {
            HBilgileri = HastaBilgileriniBul(ayiriciTcNo);
            HDTarihi = HastaninDogumTarihiniBul(ayiriciTcNo);
        } 
        catch (IOException ex) {Logger.getLogger(JHastaBilgileriniGosterVeGuncelle.class.getName()).log(Level.SEVERE, null, ex);}
        
        txtIsimSoyisim.setText(HBilgileri[0]);
        txtTcNo.setText(HBilgileri[1]);
        txtTelNo.setText(HBilgileri[2]);
        txtAdres.setText(HBilgileri[3]);
        txtDogumTarihi.setText(HDTarihi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHastaBilgileriniGuncelle = new javax.swing.JButton();
        btnGeriDon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDogumTarihi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIsimSoyisim = new javax.swing.JTextField();
        txtTcNo = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        txtAdres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHastaBilgileriniGuncelle.setBackground(new java.awt.Color(102, 153, 0));
        btnHastaBilgileriniGuncelle.setText("Hasta Bilgilerini Guncelle");
        btnHastaBilgileriniGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHastaBilgileriniGuncelleActionPerformed(evt);
            }
        });

        btnGeriDon.setText("Geri Don");
        btnGeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriDonActionPerformed(evt);
            }
        });

        jLabel1.setText("Isim Soyisim:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Hasta Bilgileri");

        jLabel6.setText("Doğum Tarihi:");

        jLabel3.setText("Tc No:");

        txtDogumTarihi.setForeground(new java.awt.Color(102, 102, 102));
        txtDogumTarihi.setText("gg-aa-yyyy");
        txtDogumTarihi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDogumTarihiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDogumTarihiFocusLost(evt);
            }
        });
        txtDogumTarihi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDogumTarihiMouseClicked(evt);
            }
        });
        txtDogumTarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDogumTarihiActionPerformed(evt);
            }
        });

        jLabel4.setText("Tel No:");

        jLabel5.setText("Adres:");

        txtTcNo.setForeground(new java.awt.Color(153, 51, 0));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("(Tc No degistirelemez)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIsimSoyisim, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(txtTcNo)
                            .addComponent(txtTelNo)
                            .addComponent(txtAdres)
                            .addComponent(txtDogumTarihi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnGeriDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(btnHastaBilgileriniGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIsimSoyisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHastaBilgileriniGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeriDon))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHastaBilgileriniGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHastaBilgileriniGuncelleActionPerformed
        // TODO add your handling code here:
        
        if(txtDogumTarihi.getText().matches("\\d{2}-\\d{2}-\\d{4}")){
            
            String xx = txtDogumTarihi.getText();
            String DTgun = Character.toString(xx.charAt(0)) + Character.toString(xx.charAt(1));
            String DTay = Character.toString(xx.charAt(3)) + Character.toString(xx.charAt(4));
            String DTyil = Character.toString(xx.charAt(6)) + Character.toString(xx.charAt(7)) + Character.toString(xx.charAt(8)) + Character.toString(xx.charAt(9));
            int currYear = Year.now().getValue();
            
            if(Integer.parseInt(DTgun)<32 && Integer.parseInt(DTay)<13 && Integer.parseInt(DTyil) < currYear+1){

                String oldstring = HBilgileri[0] + " / " +  HBilgileri[1] + " / " + HBilgileri[2] + " / " + HBilgileri[3] ;
                String newstring = txtIsimSoyisim.getText() + " / " + txtTcNo.getText() + " / " + txtTelNo.getText() + " / " + txtAdres.getText() ;

                FileGuncelle("hastaBilgileri.txt", oldstring, newstring);

                System.out.println("\n********GUNCELLENMIS GENEL\n");
                System.out.println("?"+oldstring+"?");
                System.out.println("?"+newstring+"?");

                // DOGUM TARIHINI DE GUNCELLE DIGER DOSYADAN //

                String oldstringD = HBilgileri[0] + " / " +  HBilgileri[1] + " / " + HDTarihi ;
                String newstringD = txtIsimSoyisim.getText() + " / " + HBilgileri[1] + " / " + txtDogumTarihi.getText() ;

                FileGuncelle("hastaBilgileriDogumTarihiIle.txt", oldstringD, newstringD);

                System.out.println("\n********GUNCELLENMIS DT\n");
                System.out.println("?"+oldstringD+"?");
                System.out.println("?"+newstringD+"?");


                // RANDEVU BILGILERINDEN DE DEGISTIR. GEREKSIZ O DOSYAYA GIRMEK ISTEMEDIM O YUZDEN IF KOYDUM //

                if (txtIsimSoyisim.getText().equals(HBilgileri[0]) == false){

                    String oldstringR = HBilgileri[0] + " / " +  HBilgileri[1] ;
                    String newstringR = txtIsimSoyisim.getText() + " / " + HBilgileri[1] ;

                    FileGuncelle("randevuBilgileri.txt", oldstringR, newstringR);

                }
                
                JOptionPane.showMessageDialog(this, "Hastanin bilgileri güncellendi."); 
                dispose();
                
            }else{
            JOptionPane.showMessageDialog(this, "Lütfen doğum tarihini belirli ay, gun ve yillar arasinda giriniz."); 
            }
        }else{
            JOptionPane.showMessageDialog(this, "Lütfen doğum tarihini verilen belirli formatta giriniz."); 
            txtDogumTarihi.setText("gg-aa-yyyy");
            txtDogumTarihi.setForeground(new java.awt.Color(102, 102, 102));
        }
        
    }//GEN-LAST:event_btnHastaBilgileriniGuncelleActionPerformed

    private void FileGuncelle(String filePath, String oldString, String newString){
    
        File fileToBeModified = new File(filePath);
        String oldContent = "";
        BufferedReader reader = null;
        FileWriter writer = null;
        try
        {
            reader = new BufferedReader(new FileReader(fileToBeModified));
            //Reading all the lines of input text file into oldContent
            String line = reader.readLine();
            while (line != null) 
            {
                oldContent = oldContent + line + System.lineSeparator();
                line = reader.readLine();
            }
             
            //Replacing oldString with newString in the oldContent
            String newContent = oldContent.replaceAll(oldString, newString);
            System.out.println("\n^^^^^ DEGISIM YAPILDI ^^^^^");
            System.out.println("%"+oldString+"%");
            System.out.println("%"+newString+"%");
            //Rewriting the input text file with newContent
            writer = new FileWriter(fileToBeModified);
            writer.write(newContent);
        }
        catch (IOException e)
        { e.printStackTrace();}
        finally
        {try
            {
                //Closing the resources
                reader.close();
                writer.close();
            } 
            catch (IOException e) 
            {e.printStackTrace();}
        }
                
    }
        
    
    private String HastaninDogumTarihiniBul(String TcNosu) throws FileNotFoundException, IOException{
        
        String[] normList;
        String[] HDTlist = new String[0];

        File f1=new File("hastaBilgileriDogumTarihiIle.txt"); //Creation of File Descriptor for input file
        FileReader fr = new FileReader(f1);  //Creation of File Reader object
        BufferedReader br = new BufferedReader(fr); //Creation of BufferedReader object
        String s;     
        int count=0;   //Intialize the word to zero
        
        while((s=br.readLine())!=null)   //Reading Content from the file
        {    
            normList=s.split(" / ");  //Split the word using space
            
            for (String word : normList) 
            {
                if (word.equals(TcNosu))   //Search for the given word
                {
                    count++;    //If Present increase the count by one
                    HDTlist=s.split(" / ");  //Split the word using space
                }
            }
        }
        
        if(HDTlist == null){
            System.out.println("TC bulunamadi.");
        }
        
        fr.close();       
        System.out.println("\nDT BILGILERI.");
        System.out.println(HDTlist);
        return HDTlist[2];
                
    }
    
    private String[] HastaBilgileriniBul(String TcNosu) throws FileNotFoundException, IOException{
        
        String[] normalList;
        String[] HBlist = new String[0];

        File f1=new File("hastaBilgileri.txt"); //Creation of File Descriptor for input file
        FileReader fr = new FileReader(f1);  //Creation of File Reader object
        BufferedReader br = new BufferedReader(fr); //Creation of BufferedReader object
        String s;     
        int count=0;   //Intialize the word to zero
        
        while((s=br.readLine())!=null)   //Reading Content from the file
        {    
            normalList=s.split(" / ");  //Split the word using space
            
            for (String word : normalList) 
            {
                if (word.equals(TcNosu))   //Search for the given word
                {
                    count++;    //If Present increase the count by one
                    HBlist=s.split(" / ");  //Split the word using space
                }
            }
        }
        
        if(HBlist == null){
            System.out.println("TC bulunamadi.");
        }
        
        fr.close();        
        return HBlist;
                
    }
    
    private void btnGeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriDonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnGeriDonActionPerformed

    private void txtDogumTarihiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDogumTarihiFocusGained

        if(txtDogumTarihi.getText().equals("gg-aa-yyyy")){
            txtDogumTarihi.setText("");
        }else{
            txtDogumTarihi.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtDogumTarihiFocusGained

    private void txtDogumTarihiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDogumTarihiFocusLost
        //txtDogumTarihi.setText("gg-aa-yyyy");
        if(txtDogumTarihi.getText().equals("")){
            txtDogumTarihi.setText("gg-aa-yyyy");
            txtDogumTarihi.setForeground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_txtDogumTarihiFocusLost

    private void txtDogumTarihiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDogumTarihiMouseClicked
        // TODO add your handling code here:
        if(txtDogumTarihi.getText().equals("gg-aa-yyyy")){
            txtDogumTarihi.setForeground(new java.awt.Color(102, 102, 102));
        }else{
            txtDogumTarihi.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtDogumTarihiMouseClicked

    private void txtDogumTarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDogumTarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDogumTarihiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHastaBilgileriniGosterVeGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHastaBilgileriniGosterVeGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHastaBilgileriniGosterVeGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHastaBilgileriniGosterVeGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHastaBilgileriniGosterVeGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeriDon;
    private javax.swing.JButton btnHastaBilgileriniGuncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtDogumTarihi;
    private javax.swing.JTextField txtIsimSoyisim;
    private javax.swing.JTextField txtTcNo;
    private javax.swing.JTextField txtTelNo;
    // End of variables declaration//GEN-END:variables
}
