/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastatakip;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author esmasert
 */
public class JYeniHastaRandevuBilgileri extends javax.swing.JFrame {

    /**
     * Creates new form JYeniHastaRandevuBilgileri
     */
    public JYeniHastaRandevuBilgileri() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        setDefaultCloseOperation(JYeniHastaRandevuBilgileri.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSikayet = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMuayene = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTahlil = new javax.swing.JTextArea();
        btnPDF = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTeshis = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTedavi = new javax.swing.JTextArea();
        btnBilgileriKaydet = new javax.swing.JButton();
        btnRanBlgGeriDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 136, 196));
        jLabel1.setText("Yeni Hasta Randevu Bilgileri");

        jLabel2.setText("Şikayet:");

        jLabel3.setText("Muayene:");

        jLabel4.setText("Tahlil:");

        jLabel5.setText("Teşhis:");

        jLabel6.setText("Tedavi:");

        txtSikayet.setColumns(20);
        txtSikayet.setRows(5);
        jScrollPane1.setViewportView(txtSikayet);

        txtMuayene.setColumns(20);
        txtMuayene.setRows(5);
        jScrollPane2.setViewportView(txtMuayene);

        txtTahlil.setColumns(20);
        txtTahlil.setRows(5);
        jScrollPane3.setViewportView(txtTahlil);

        btnPDF.setText("PDF");

        txtTeshis.setColumns(20);
        txtTeshis.setRows(5);
        jScrollPane4.setViewportView(txtTeshis);

        txtTedavi.setColumns(20);
        txtTedavi.setRows(5);
        jScrollPane5.setViewportView(txtTedavi);

        btnBilgileriKaydet.setBackground(new java.awt.Color(102, 153, 0));
        btnBilgileriKaydet.setText("Bilgileri Kaydet");
        btnBilgileriKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilgileriKaydetActionPerformed(evt);
            }
        });

        btnRanBlgGeriDon.setText("Geri Dön");
        btnRanBlgGeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRanBlgGeriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPDF)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnRanBlgGeriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBilgileriKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPDF)
                                .addGap(17, 17, 17))))
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBilgileriKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRanBlgGeriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRanBlgGeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRanBlgGeriDonActionPerformed
        // TODO add your handling code here:
        
        JYeniHasta JYeniHastaFrame = new JYeniHasta();
        JYeniHastaFrame.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_btnRanBlgGeriDonActionPerformed

    private void btnBilgileriKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilgileriKaydetActionPerformed
        // TODO add your handling code here:
        
        String hastaRandevuBilgileriData[] = {txtSikayet.getText(),txtMuayene.getText(),txtTahlil.getText(),txtTeshis.getText(),txtTedavi.getText()};
        
        if(txtSikayet.getText().equals("")|| txtMuayene.getText().equals("")||txtTahlil.getText().equals("")||txtTeshis.getText().equals("")||txtTedavi.getText().equals("")){
        
            // if any field left blank than show message
            
            JOptionPane.showMessageDialog(this, "Lütfen boş alan bırakmayınız.");   
        }else{
        
            try(FileWriter fw2 = new FileWriter("randevuBilgileri.txt", true);
                BufferedWriter bw2 = new BufferedWriter(fw2);
                PrintWriter out2 = new PrintWriter(bw2))
            {
                
                int len = hastaRandevuBilgileriData.length;
                for (int i=0;i<len-1;i++) {
                    out2.print(hastaRandevuBilgileriData[i]);
                    out2.print(" / ");
                }
                out2.print(hastaRandevuBilgileriData[len-1]);

                //JOptionPane.showMessageDialog(this, "Başarıyla kaydedildi."); 
                
                out2.print(" / ");
                out2.print(java.time.LocalDate.now());
                //out2.print(" / ");
                //out2.print(java.time.LocalTime.now());
                

            } catch (IOException e) {
                //exception handling left as an exercise for the reader
            }
        
            
            //JTable UpdateTableInYH = new JTable();
            //UpdateTableInYH.UpdateTable();

            //JTable CloseBeforeMainWindow = new JTable();
            //CloseBeforeMainWindow.CloseThisFramee();

            JTable JTableFrame = new JTable();
            JTableFrame.setVisible(true);

            //setDefaultCloseOperation(JYeniHasta.DISPOSE_ON_CLOSE);
            //JYeniHasta.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
            setVisible(false); //you can't see me!
            dispose(); //Destroy the JFrame object

            //JTable.this.reset();

            JOptionPane.showMessageDialog(this, "Hasta randevu bilgileri başarıyla kaydedildi ve liste güncellendi."); 

        }
        
    }//GEN-LAST:event_btnBilgileriKaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JYeniHastaRandevuBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JYeniHastaRandevuBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JYeniHastaRandevuBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JYeniHastaRandevuBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JYeniHastaRandevuBilgileri().setVisible(true);
            }
        });
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilgileriKaydet;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRanBlgGeriDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txtMuayene;
    private javax.swing.JTextArea txtSikayet;
    private javax.swing.JTextArea txtTahlil;
    private javax.swing.JTextArea txtTedavi;
    private javax.swing.JTextArea txtTeshis;
    // End of variables declaration//GEN-END:variables
}
